services:
  frontend:
    build:
      context: frontend/
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000

  redis:
    image: "redis"
    ports:
      - 6379:6379

  backend:
    build:
      context: backend/
    develop:
      watch: 
        - path: ./backend/
          action: sync+restart
          target: /rails
    ports:
      - 4000:3000
    volumes:
      - ./backend/storage/production.sqlite3:/rails/storage/production.sqlite3


